# mysql -p
> CREATE DATABASE portal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
> CREATE USER 'portal'@'%' IDENTIFIED BY 'top-secret';
> GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, CREATE, DROP, INDEX, LOCK TABLES, REFERENCES ON portal.* TO 'portal'@'%';
> QUIT;
