#!/bin/bash
# JBoss 7.x EAP invoke script
# Copyright (c) 2018 - Reinaldo Gil Lima de Carvalho <reinaldoc@gmail.com>

### BEGIN INIT INFO
# Provides:          jboss7
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: JBoss 7.x EAP invoke script
### END INIT INFO

### CONFIG
MESSAGE='Java Application Server: jboss7 EAP'
GETPID='org.jboss.as.standalone'
SERVICEUSER='jboss'
SERVICECMD='{ARG1}/bin/standalone.sh -b 0.0.0.0 >/dev/null 2>&1 &'

### END CONFIG

#
# Return execution status
#
# @param $1 string to be checked
# @return int
function isEmpty {
	[[ $1 =~ ^[[:space:]]*$ ]]
	return $?
}

#
# Set $PROCPID with service pid
#
# @param $1 service work directory
# @return void
#
function setPid() {
	PROCPID=$(ps -ef | grep "${GETPID}" | grep -v ' grep ' | tr -s ' ' | cut -f2 -d ' ')
}

#
# Kill managed PID
#
# @param $1 optional kill signal
# @return void
function killPid() {
	if ! isEmpty "$PROCPID" ; then
		kill "$1" "$PROCPID" > /dev/null 2>&1
	fi
}

#
# Start Service
#
# @param  $1   service work directory
# @return void
function startService() {

	if isEmpty "$1"; then
		echo "Err: service work directory is required as argument."
		return
	fi

	echo -n "Starting $MESSAGE"
	setPid "$1"
	if isEmpty "$PROCPID"; then
		cmd=$(sed -re "s@\{ARG1\}@$1@" <<< $SERVICECMD)
		su -l $SERVICEUSER -s /bin/bash -c "$cmd"
		echo " ($1)."
	else
		echo " ($1 already started)."
	fi
}

#
# Stop Service
#
# @param  $1   service work directory
# @return void
function stopService() {
	if isEmpty "$1"; then
		echo "Err: service work directory is required as argument."
		return
	fi

	echo -n "Stopping $MESSAGE"
	setPid "$1"
	if isEmpty "$PROCPID"; then
		echo " ($1 already stopped)."
		return
	fi

	killPid
	i=0
	while true; do
		setPid "$1"
		if ! isEmpty "$PROCPID" ; then
			if [ $i -gt 15 ] ; then
				killPid -9
			elif [ $i -gt 10 ] ; then
				killPid
			fi
			echo -n .
			sleep 2
		else
			break
		fi
		let i++
	done
	echo .
}

case "$1" in
	start)
		startService /srv/jboss-eap-7.1
	;;
	stop)
		stopService /srv/jboss-eap-7.1
	;;
	restart)
		stopService /srv/jboss-eap-7.1
		startService /srv/jboss-eap-7.1
	;;
	*)
		echo "Usage: $0 {start | stop | restart}"
		exit 1
	;;
esac

exit 0
