#!/bin/bash
# Solr 4.x invoke script
# Copyright (c) 2018 - Reinaldo Gil Lima de Carvalho <reinaldoc@gmail.com>

### BEGIN INIT INFO
# Provides:          solr4
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Solr4 invoke script
### END INIT INFO

### CONFIG
STARTMESSAGE='Starting Search Server: solr4'
STOPMESSAGE='Stopping Search Server: solr4'
GETPID='java -jar start.jar'

### END CONFIG

#
# Return execution status
#
# @param $1 string to be checked
# @return int
function isEmpty {
	[[ $1 =~ ^[[:space:]]*$ ]]
	return $?
}

#
# Set $PROCPID with service pid
#
# @param $1 service work directory
# @return void
#
function setPid() {
	PROCPID=$(ps -ef | grep "${GETPID}" | grep -v ' grep ' | tr -s ' ' | cut -f2 -d ' ')
}

#
# Kill managed PID
#
# @param $1 optional kill signal
# @return void
function killPid() {
	if ! isEmpty "$PROCPID" ; then
		kill "$1" "$PROCPID" > /dev/null 2>&1
	fi
}

#
# Start Service
#
# @param  $1   service work directory
# @return void
function startService() {

	if isEmpty "$1"; then
		echo "Err: service work directory is required as argument."
		return
	fi

	if isEmpty "$2"; then
		echo "Err: service port is required as argument."
		return
	fi

	echo -n $STARTMESSAGE
	setPid "$1"
	if isEmpty "$PROCPID"; then
		su -l solr -s /bin/bash -c "cd $1; java -jar start.jar -Djetty.port=$2 >/dev/null 2>&1 &"
		echo " ($1)."
	else
		echo " ($1 already started)."
	fi
}

#
# Stop Service
#
# @param  $1   service work directory
# @return void
function stopService() {
	if isEmpty "$1"; then
		echo "Err: service work directory is required as argument."
		return
	fi

	echo -n $STOPMESSAGE
	setPid "$1"
	if isEmpty "$PROCPID"; then
		echo " ($1 already stopped)."
		return
	fi

	killPid
	i=0
	while true; do
		setPid "$1"
		if ! isEmpty "$PROCPID" ; then
			if [ $i -gt 15 ] ; then
				killPid -9
			elif [ $i -gt 10 ] ; then
				killPid
			fi
			echo -n .
			sleep 2
		else
			break
		fi
		let i++
	done
	echo .
}

case "$1" in
	start)
		startService /srv/apache-solr-4.0.0/instance1 8983
	;;
	stop)
		stopService /srv/apache-solr-4.0.0/instance1
	;;
	restart)
		stopService /srv/apache-solr-4.0.0/instance1
		startService /srv/apache-solr-4.0.0/instance1 8983
	;;
	*)
		echo "Usage: $0 {start | stop | restart}"
		exit 1
	;;
esac

exit 0
